Criar um dataset com as 43 empresas cotadas em Bolsa

In [1]:
import pandas as pd

empresas = pd.read_csv(
    "Euronext_Equities_2026-04-07.csv",
    sep=";",
    skiprows=[1, 2, 3]

)

empresas.head()

,Name,ISIN,Symbol,Market,Currency,Open Price,High Price,low Price,last Price,last Trade MIC Time,Time Zone,Volume,Turnover,Closing Price,Closing Price DateTime
0,ALTRI SGPS,PTALT0AE0002,ALTR,Euronext Lisbon,EUR,4.91,4.985,4.82,4.835,02/04/2026 21:35,BST,544062,2654995.26,4.835,02/04/2026
1,ARRABIDASHOPPING,PTCAP0AM0017,MLARR,Euronext Access Lisbon,EUR,-,-,-,-,-,BST,-,-,-,-
2,ATRIUM BIRE SIGI,PTTBI0AM0006,MLATR,Euronext Access Lisbon,EUR,2.98,2.98,2.98,2.98,05/08/2025 21:00,BST,16780,50004.40,2.98,02/04/2026
3,B.COM.PORTUGUES,PTBCP0AM0015,BCP,Euronext Lisbon,EUR,0.86,0.868,0.8488,0.8646,02/04/2026 21:35,BST,69179682,59416046.70,0.8646,02/04/2026
4,BENFICA,PTSLB0AM0010,SLBEN,Euronext Lisbon,EUR,6.36,6.62,6.34,6.34,02/04/2026 15:59,BST,273,1787.28,6.34,02/04/2026

In [3]:
empresas = empresas[empresas["Open Price"] != "-"]
empresas = empresas.iloc[:, [0]]
empresas.head(10)

                  Name
0           ALTRI SGPS
2     ATRIUM BIRE SIGI
3      B.COM.PORTUGUES
4              BENFICA
5   CIAGEST - SIGI S.A
6             CONDURIL
7    CORTICEIRA AMORIM
8    CTT CORREIOS PORT
9                  EDP
10      EDP RENOVAVEIS

In [4]:
empresas.to_csv("empresas.csv", index = False)

In [10]:
edges = pd.read_csv("edges.csv")
edges.head(10)

                           source            target  weight
0       promendo_investimentos_sa        altri_sgps   17.54
1                 caderno_azul_sa        altri_sgps   16.67
2               actium_capital_sa        altri_sgps   14.17
3  vieira_de_matos_vdm_capital_sa        altri_sgps   12.35
4          1_thing_investments_sa        altri_sgps   10.01
5       bankinter_private_clients  atrium_bire_sigi   66.25
6   kostas_holding_unipessoal_lda  atrium_bire_sigi   20.00
7         bankinter_investment_sa  atrium_bire_sigi   10.00
8  sierra_developments_holding_bv  atrium_bire_sigi    3.75
9                    groupe_fosun     bcomportugues   20.03

In [11]:
edges.info()

<class 'pandas.DataFrame'>
RangeIndex: 153 entries, 0 to 152
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   source  153 non-null    str
 1   target  153 non-null    str
 2   weight  153 non-null    float64
dtypes: float64(1), str(2)
memory usage: 3.7 KB